[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
is-system = true # as of recording you instead need to add --system-mode-true into command line whne u compile
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
